### ISSUE TITLE
Getting Code To Work

### ISSUE THREAD

**Issue by artforlife** [lancelote/django_by_example#10]
I realize that you are not the author of the book, but am writing this here nonetheless. Have you been able to get the code to work on Chapter 1? When I finished it, all I see are the results of template outputs, but they do not contain the Posts information even though I have some created inside the database. 

At first I thought that I had made a mistake somewhere; however, I also tried to run the code that comes with the book and it produces the same exact result. I even copied my SQLite file inside the book code's directory and ran it like that to no avail. 

Do you have any idea about what could be happening?

**Comment by lancelote** [comment]
Hi @artforlife ! Are the posts you created drafts or published? I believe drafts will not be shown in the list.

**Comment by artforlife** [comment]
You were right. That is exactly what happened!
